# Generated by Django 3.1.1 on 2020-09-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
