# Generated by Django 3.1.1 on 2020-09-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200905_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
